In [1]:
import numpy as np

In [2]:
# Sigmoid function
def nonlin(x, deriv=False):
    if deriv:
        return x*(1 - x)
    return 1/(1+np.exp(-x))

In [3]:
# Input dataset
X = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])

# Labels dataset
y = np.array([[0, 0, 1, 1]]).T

In [4]:
# initialize weights with 0.5
syn0 = np.array([[0.5, 0.5, 0.5]]).T

In [5]:
for i in range(100):
    # forward propagation
    l0 = X
    l0_sigmoid = np.dot(l0, syn0)
    l1 = nonlin(l0_sigmoid)

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the
    # slope of the sigmoid at the values in l1
    l1_deriv_sigmoid = nonlin(l1,True)
    l1_delta = l1_error * l1_deriv_sigmoid

    # update weights
    syn0 += np.dot(l0.T, l1_delta)

In [6]:
print('Input:')
print(X)
print('Output After Training:')
print(l1)
print('Final Weights:')
print(syn0)
sample = np.array([1, 0, 1]).T
print('Predict', sample, 'sample:')
sample_dot_syn = np.dot(sample, syn0)
predict = nonlin(sample_dot_syn)
print(predict)

Input:
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
Output After Training:
[[0.11395525]
 [0.09107105]
 [0.92702319]
 [0.90822661]]
Final Weights:
[[ 4.60538482]
 [-0.24955452]
 [-2.05741984]]
Predict [1 0 1] sample:
[0.92743668]
