In [1]:
import numpy as np

In [2]:
# Sigmoid function
def nonlin(x, deriv=False):
    if deriv:
        return x*(1 - x)
    return 1/(1+np.exp(-x))

In [3]:
# Input dataset
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
# Labels dataset
y = np.array([[0], [1], [1], [0]])

np.random.seed(1)
# randomly initialize our weights with mean 0
syn0 = 2 * np.random.random((2, 3)) - 1
syn1 = 2 * np.random.random((3, 1)) - 1

In [4]:
print(syn0)
print(syn1)

[[-0.16595599  0.44064899 -0.99977125]
 [-0.39533485 -0.70648822 -0.81532281]]
[[-0.62747958]
 [-0.30887855]
 [-0.20646505]]


In [5]:
for j in range(1500):

    # Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))

    # how much did we miss the target value?
    l2_error = y - l2

    if (j % 150) == 0:
        print('Forward pass' , j , 'Error:' + str(np.mean(np.abs(l2_error))))

    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error * nonlin(l2, deriv=True)

    # how much did each l1 value contribute to the l2 error
    # (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)

    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1, deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

Forward pass 0 Error:0.4992921119953979
Forward pass 150 Error:0.4771554081054314
Forward pass 300 Error:0.38304617817018616
Forward pass 450 Error:0.3173694219357399
Forward pass 600 Error:0.25241172680853347
Forward pass 750 Error:0.21993640499000577
Forward pass 900 Error:0.2025032038308218
Forward pass 1050 Error:0.1915963211253034
Forward pass 1200 Error:0.18405081482700453
Forward pass 1350 Error:0.17846998655902918


In [6]:
print('syn0')
print(syn0)
print('syn1')
print(syn1)

syn0
[[-7.15687333  1.56550571 -5.18410514]
 [ 1.51471769 -7.24098189 -5.39567567]]
syn1
[[  3.36880838]
 [  3.36096492]
 [-12.01816063]]
