In [1]:
import numpy as np

In [2]:
# Sigmoid function
def nonlin(x, deriv=False):
    if deriv:
        return x*(1 - x)
    return 1/(1+np.exp(-x))

In [3]:
# Input dataset
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
# Labels dataset
y = np.array([[0], [1], [1], [0]])

np.random.seed(1)
# randomly initialize our weights with mean 0
syn0 = 2 * np.random.random((2, 3)) - 1
syn1 = 2 * np.random.random((3, 1)) - 1

In [4]:
print(syn0)
print(syn1)

[[-0.16595599  0.44064899 -0.99977125]
 [-0.39533485 -0.70648822 -0.81532281]]
[[-0.62747958]
 [-0.30887855]
 [-0.20646505]]


In [9]:
for j in range(1):

    # Feed forward through layers 0, 1, and 2
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))
    #print(np.dot(l0, syn0))
    #print(l1)
    l2 = nonlin(np.dot(l1, syn1))
    print(l2)
    # how much did we miss the target value?
    l2_error = y - l2

    if (j % 150) == 0:
        print('Forward pass' , j , 'Error:' + str(np.mean(np.abs(l2_error))))

    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error * nonlin(l2, deriv=True)
    print (nonlin(l2, deriv=True))
    # how much did each l1 value contribute to the l2 error
    # (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)

    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * nonlin(l1, deriv=True)

    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

[[0.0421063 ]
 [0.9616978 ]
 [0.96179389]
 [0.50220117]]
Forward pass 0 Error:0.15520394258871545
[[0.04033336]
 [0.03683514]
 [0.0367464 ]
 [0.24999515]]


In [10]:
print('syn0')
print(syn0)
print('syn1')
print(syn1)

syn0
[[-9.16579952  1.90300723 -5.40608348]
 [ 1.87972779 -9.20388491 -5.56532905]]
syn1
[[  4.07963395]
 [  4.08050102]
 [-14.906136  ]]
